"""OntoGen settings bridged to ../config.py."""

import os
from pathlib import Path
import sys


ONTOLOGYM_ROOT = Path(__file__).resolve().parents[1]
if str(ONTOLOGYM_ROOT) not in sys.path:
    sys.path.insert(0, str(ONTOLOGYM_ROOT))

from common.project_config import load_env_file, load_project_config


_project = load_project_config()
load_env_file(getattr(_project, "ENV_FILE", ONTOLOGYM_ROOT / ".env"))


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# =============================================================================
# User settings
# =============================================================================

# Project folders. User-facing values live in ../config.py.
PROJECT_ROOT = Path(__file__).resolve().parent
RUN_OUTPUT_DIR = getattr(_project, "RUN_OUTPUT_DIR", ONTOLOGYM_ROOT / "data")
DATA_DIR = getattr(_project, "ONTOGEN_DATA_DIR", ONTOLOGYM_ROOT / "data" / "ontogen")
PDF_DIR = getattr(_project, "SHARED_PAPER_DIR", DATA_DIR / "pdfs")
TEXT_DIR = getattr(_project, "ONTOGEN_TEXT_DIR", DATA_DIR / "text")
SECTION_DIR = getattr(_project, "ONTOGEN_SECTION_DIR", DATA_DIR / "sections")
TABLE_DIR = getattr(_project, "ONTOGEN_TABLE_DIR", DATA_DIR / "tables")
PROCESSED_DATA_DIR = getattr(_project, "ONTOGEN_PROCESSED_DATA_DIR", DATA_DIR / "processed_data")
ENRICHED_DIR = getattr(_project, "ONTOGEN_ENRICHED_DIR", DATA_DIR / "enriched")
TERMO_DIR = getattr(_project, "ONTOGEN_TERMO_DIR", DATA_DIR / "termo")
CATEGORY_DIR = getattr(_project, "ONTOGEN_CATEGORY_DIR", DATA_DIR / "categories")
TAXONOMY_DIR = getattr(_project, "ONTOGEN_TAXONOMY_DIR", DATA_DIR / "taxonomy")

# List PDF or parsed JSON file names/paths. If empty, run.py discovers inputs in PDF_DIR.
PDF_FILES = getattr(_project, "ONTOGEN_PDF_FILES", [])
RECURSIVE_PDF_DISCOVERY = getattr(_project, "ONTOGEN_RECURSIVE_PDF_DISCOVERY", True)
INCLUDE_PARSED_JSON_INPUTS = getattr(_project, "ONTOGEN_INCLUDE_PARSED_JSON_INPUTS", True)

# Pipeline switches. Keep expensive LLM/Nougat steps off until you are ready.
RUN_PDF_TO_TEXT = getattr(_project, "ONTOGEN_RUN_PDF_TO_TEXT", False)
RUN_SECTION_EXTRACTION = getattr(_project, "ONTOGEN_RUN_SECTION_EXTRACTION", False)
RUN_TABLE_EXTRACTION = getattr(_project, "ONTOGEN_RUN_TABLE_EXTRACTION", False)
RUN_PROCESSED_DATA_BUILD = getattr(_project, "ONTOGEN_RUN_PROCESSED_DATA_BUILD", True)
RUN_BUILD_ENRICHED_CONTEXT = getattr(_project, "ONTOGEN_RUN_BUILD_ENRICHED_CONTEXT", False)
RUN_TERMO = getattr(_project, "ONTOGEN_RUN_TERMO", False)
RUN_CATEGORY_GENERATION = getattr(_project, "ONTOGEN_RUN_CATEGORY_GENERATION", False)
RUN_TAXONOMY_GENERATION = getattr(_project, "ONTOGEN_RUN_TAXONOMY_GENERATION", False)
REUSE_INTERMEDIATE_OUTPUTS = _env_bool(
    "ONTOLOGYM_ONTOGEN_REUSE_INTERMEDIATE_OUTPUTS",
    getattr(_project, "ONTOGEN_REUSE_INTERMEDIATE_OUTPUTS", False),
)

# Text extraction backend. Use "pymupdf" for a lighter run or "nougat" for
# markdown-like section structure when Nougat is installed and available.
TEXT_SOURCE = getattr(_project, "ONTOGEN_TEXT_SOURCE", "pymupdf")  # "nougat" or "pymupdf"

# Evidence-aware section and table settings.
SECTIONS_TO_EXTRACT = getattr(_project, "ONTOGEN_SECTIONS_TO_EXTRACT", [
    "abstract",
    "introduction",
    "methods",
    "experimental",
    "experiments",
    "evaluation",
    "results",
    "discussion",
    "ablation",
])
INCLUDE_SECTIONS_IN_ENRICHED_CONTEXT = getattr(
    _project,
    "ONTOGEN_INCLUDE_SECTIONS_IN_ENRICHED_CONTEXT",
    SECTIONS_TO_EXTRACT,
)
EXTRACT_TABLES = getattr(_project, "ONTOGEN_EXTRACT_TABLES", True)
INCLUDE_TABLES_IN_ENRICHED_CONTEXT = getattr(_project, "ONTOGEN_INCLUDE_TABLES_IN_ENRICHED_CONTEXT", True)
PROCESSED_DATA_SOURCE = getattr(_project, "ONTOGEN_PROCESSED_DATA_SOURCE", "existing")
AIRQA_PROCESSED_DATA_DIR = getattr(_project, "QA_PROCESSED_DATA_DIR", None)
USE_PROCESSED_DATA_FOR_ENRICHED_CONTEXT = getattr(_project, "ONTOGEN_USE_PROCESSED_DATA_FOR_ENRICHED_CONTEXT", True)
INCLUDE_FIGURE_CAPTIONS_IN_ENRICHED_CONTEXT = getattr(
    _project,
    "ONTOGEN_INCLUDE_FIGURE_CAPTIONS_IN_ENRICHED_CONTEXT",
    False,
)
INCLUDE_EQUATIONS_IN_ENRICHED_CONTEXT = getattr(_project, "ONTOGEN_INCLUDE_EQUATIONS_IN_ENRICHED_CONTEXT", False)
ENRICHED_MAX_CHARS_PER_PAPER = getattr(_project, "ONTOGEN_ENRICHED_MAX_CHARS_PER_PAPER", None)

# TERMO settings.
TERMO_MODEL = getattr(_project, "ONTOGEN_TERMO_MODEL", "llama3.1:70b")
TERMO_BACKEND = getattr(_project, "ONTOGEN_TERMO_BACKEND", "ollama")
TERMO_TEMPERATURE = getattr(_project, "ONTOGEN_TERMO_TEMPERATURE", 0.1)
TERMO_NUM_CTX = getattr(_project, "ONTOGEN_TERMO_NUM_CTX", 9000)
TERMO_BASE_URL = getattr(_project, "ONTOGEN_TERMO_BASE_URL", None)
TERMO_REASONING_EFFORT = getattr(_project, "ONTOGEN_TERMO_REASONING_EFFORT", None)
TERMO_MAX_COMPLETION_TOKENS = getattr(_project, "ONTOGEN_TERMO_MAX_COMPLETION_TOKENS", None)

RUN_TERMO_TERMS = getattr(_project, "ONTOGEN_RUN_TERMO_TERMS", True)
RUN_TERMO_ACRONYMS = getattr(_project, "ONTOGEN_RUN_TERMO_ACRONYMS", True)
RUN_TERMO_DEFINITIONS = getattr(_project, "ONTOGEN_RUN_TERMO_DEFINITIONS", True)
RUN_TERMO_RELATIONSHIPS = getattr(_project, "ONTOGEN_RUN_TERMO_RELATIONSHIPS", True)

TERMO_TERMS_MODEL = getattr(_project, "ONTOGEN_TERMO_TERMS_MODEL", TERMO_MODEL)
TERMO_TERMS_BACKEND = getattr(_project, "ONTOGEN_TERMO_TERMS_BACKEND", TERMO_BACKEND)
TERMO_TERMS_TEMPERATURE = getattr(_project, "ONTOGEN_TERMO_TERMS_TEMPERATURE", TERMO_TEMPERATURE)
TERMO_TERMS_NUM_CTX = getattr(_project, "ONTOGEN_TERMO_TERMS_NUM_CTX", TERMO_NUM_CTX)
TERMO_TERMS_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_TERMO_TERMS_MAX_COMPLETION_TOKENS",
    TERMO_MAX_COMPLETION_TOKENS,
)
TERMO_TERMS_REASONING_EFFORT = getattr(_project, "ONTOGEN_TERMO_TERMS_REASONING_EFFORT", TERMO_REASONING_EFFORT)
TERMO_TERMS_BASE_URL = getattr(_project, "ONTOGEN_TERMO_TERMS_BASE_URL", TERMO_BASE_URL)

TERMO_ACRONYMS_MODEL = getattr(_project, "ONTOGEN_TERMO_ACRONYMS_MODEL", TERMO_MODEL)
TERMO_ACRONYMS_BACKEND = getattr(_project, "ONTOGEN_TERMO_ACRONYMS_BACKEND", TERMO_BACKEND)
TERMO_ACRONYMS_TEMPERATURE = getattr(_project, "ONTOGEN_TERMO_ACRONYMS_TEMPERATURE", TERMO_TEMPERATURE)
TERMO_ACRONYMS_NUM_CTX = getattr(_project, "ONTOGEN_TERMO_ACRONYMS_NUM_CTX", TERMO_NUM_CTX)
TERMO_ACRONYMS_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_TERMO_ACRONYMS_MAX_COMPLETION_TOKENS",
    TERMO_MAX_COMPLETION_TOKENS,
)
TERMO_ACRONYMS_REASONING_EFFORT = getattr(
    _project,
    "ONTOGEN_TERMO_ACRONYMS_REASONING_EFFORT",
    TERMO_REASONING_EFFORT,
)
TERMO_ACRONYMS_BASE_URL = getattr(_project, "ONTOGEN_TERMO_ACRONYMS_BASE_URL", TERMO_BASE_URL)

TERMO_DEFINITIONS_MODEL = getattr(_project, "ONTOGEN_TERMO_DEFINITIONS_MODEL", TERMO_MODEL)
TERMO_DEFINITIONS_BACKEND = getattr(_project, "ONTOGEN_TERMO_DEFINITIONS_BACKEND", TERMO_BACKEND)
TERMO_DEFINITIONS_TEMPERATURE = getattr(_project, "ONTOGEN_TERMO_DEFINITIONS_TEMPERATURE", TERMO_TEMPERATURE)
TERMO_DEFINITIONS_NUM_CTX = getattr(_project, "ONTOGEN_TERMO_DEFINITIONS_NUM_CTX", TERMO_NUM_CTX)
TERMO_DEFINITIONS_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_TERMO_DEFINITIONS_MAX_COMPLETION_TOKENS",
    TERMO_MAX_COMPLETION_TOKENS,
)
TERMO_DEFINITIONS_REASONING_EFFORT = getattr(
    _project,
    "ONTOGEN_TERMO_DEFINITIONS_REASONING_EFFORT",
    TERMO_REASONING_EFFORT,
)
TERMO_DEFINITIONS_BASE_URL = getattr(_project, "ONTOGEN_TERMO_DEFINITIONS_BASE_URL", TERMO_BASE_URL)

TERMO_RELATIONSHIPS_MODEL = getattr(_project, "ONTOGEN_TERMO_RELATIONSHIPS_MODEL", TERMO_MODEL)
TERMO_RELATIONSHIPS_BACKEND = getattr(_project, "ONTOGEN_TERMO_RELATIONSHIPS_BACKEND", TERMO_BACKEND)
TERMO_RELATIONSHIPS_TEMPERATURE = getattr(_project, "ONTOGEN_TERMO_RELATIONSHIPS_TEMPERATURE", TERMO_TEMPERATURE)
TERMO_RELATIONSHIPS_NUM_CTX = getattr(_project, "ONTOGEN_TERMO_RELATIONSHIPS_NUM_CTX", TERMO_NUM_CTX)
TERMO_RELATIONSHIPS_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_TERMO_RELATIONSHIPS_MAX_COMPLETION_TOKENS",
    TERMO_MAX_COMPLETION_TOKENS,
)
TERMO_RELATIONSHIPS_REASONING_EFFORT = getattr(
    _project,
    "ONTOGEN_TERMO_RELATIONSHIPS_REASONING_EFFORT",
    TERMO_REASONING_EFFORT,
)
TERMO_RELATIONSHIPS_BASE_URL = getattr(_project, "ONTOGEN_TERMO_RELATIONSHIPS_BASE_URL", TERMO_BASE_URL)

TERMO_MAX_LENGTH_SPLIT_TERMS = getattr(_project, "ONTOGEN_TERMO_MAX_LENGTH_SPLIT_TERMS", 2000)
TERMO_MAX_LENGTH_SPLIT_ACRONYMS = getattr(_project, "ONTOGEN_TERMO_MAX_LENGTH_SPLIT_ACRONYMS", 2000)
TERMO_MAX_LENGTH_SPLIT_DEFINITIONS = getattr(_project, "ONTOGEN_TERMO_MAX_LENGTH_SPLIT_DEFINITIONS", 10000)
TERMO_MAX_LENGTH_SPLIT_RELATIONSHIPS = getattr(_project, "ONTOGEN_TERMO_MAX_LENGTH_SPLIT_RELATIONSHIPS", 10000)
CONTEXT_KIND = getattr(_project, "ONTOGEN_CONTEXT_KIND", "enriched")
RELATIONSHIP_MODE = getattr(_project, "ONTOGEN_RELATIONSHIP_MODE", "evidence")
INCLUDE_LITERAL_VALUES = getattr(_project, "ONTOGEN_INCLUDE_LITERAL_VALUES", True)
PRESERVE_TABLE_BLOCKS = getattr(_project, "ONTOGEN_PRESERVE_TABLE_BLOCKS", True)
REMOVE_HALLUCINATED_TERMS = getattr(_project, "ONTOGEN_REMOVE_HALLUCINATED_TERMS", True)
SKIP_ACRONYMS = not RUN_TERMO_ACRONYMS
SKIP_DEFINITIONS = not RUN_TERMO_DEFINITIONS
SKIP_RELATIONSHIPS = not RUN_TERMO_RELATIONSHIPS

# Domain and category generation settings.
DOMAIN_NAME = getattr(_project, "ONTOGEN_DOMAIN_NAME", "Scientific Literature")
EVIDENCE_AWARE_CATEGORIES = getattr(_project, "ONTOGEN_EVIDENCE_AWARE_CATEGORIES", True)
CATEGORY_GENERATION_MODEL = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_MODEL", "llama3.1:8b-instruct-fp16")
CATEGORY_FORMAT_MODEL = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_MODEL", "llama3.1:70b")
CATEGORY_SYNTHESIS_MODEL = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_MODEL", "llama3.1:70b")
CATEGORY_GENERATION_BACKEND = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_BACKEND", "ollama")
CATEGORY_FORMAT_BACKEND = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_BACKEND", CATEGORY_GENERATION_BACKEND)
CATEGORY_SYNTHESIS_BACKEND = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_BACKEND", CATEGORY_GENERATION_BACKEND)
CATEGORY_GENERATION_BASE_URL = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_BASE_URL", None)
CATEGORY_FORMAT_BASE_URL = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_BASE_URL", CATEGORY_GENERATION_BASE_URL)
CATEGORY_SYNTHESIS_BASE_URL = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_BASE_URL", CATEGORY_GENERATION_BASE_URL)
CATEGORY_GENERATION_TEMPERATURE = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_TEMPERATURE", 0.5)
CATEGORY_GENERATION_NUM_CTX = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_NUM_CTX", 16000)
CATEGORY_GENERATION_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_CATEGORY_GENERATION_MAX_COMPLETION_TOKENS",
    None,
)
CATEGORY_MAX_CHARS_PER_FILE = getattr(_project, "ONTOGEN_CATEGORY_MAX_CHARS_PER_FILE", None)
CATEGORY_MAX_TOTAL_CHARS = getattr(_project, "ONTOGEN_CATEGORY_MAX_TOTAL_CHARS", None)
CATEGORY_GENERATION_REASONING_EFFORT = getattr(_project, "ONTOGEN_CATEGORY_GENERATION_REASONING_EFFORT", None)
CATEGORY_FORMAT_TEMPERATURE = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_TEMPERATURE", None)
CATEGORY_FORMAT_NUM_CTX = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_NUM_CTX", 16000)
CATEGORY_FORMAT_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_CATEGORY_FORMAT_MAX_COMPLETION_TOKENS",
    None,
)
CATEGORY_FORMAT_REASONING_EFFORT = getattr(_project, "ONTOGEN_CATEGORY_FORMAT_REASONING_EFFORT", None)
CATEGORY_SYNTHESIS_TEMPERATURE = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_TEMPERATURE", None)
CATEGORY_SYNTHESIS_NUM_CTX = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_NUM_CTX", 16000)
CATEGORY_SYNTHESIS_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_CATEGORY_SYNTHESIS_MAX_COMPLETION_TOKENS",
    None,
)
CATEGORY_SYNTHESIS_REASONING_EFFORT = getattr(_project, "ONTOGEN_CATEGORY_SYNTHESIS_REASONING_EFFORT", None)
CATEGORY_NUM_RETRIES = getattr(_project, "ONTOGEN_CATEGORY_NUM_RETRIES", 5)
CATEGORY_NUM_GENERATED_SEED = getattr(_project, "ONTOGEN_CATEGORY_NUM_GENERATED_SEED", 5)
CATEGORY_RUN_LLM_CURATION = getattr(_project, "ONTOGEN_CATEGORY_RUN_LLM_CURATION", False)
CATEGORY_CURATION_RATIO = getattr(_project, "ONTOGEN_CATEGORY_CURATION_RATIO", None)
CATEGORY_CURATION_TARGET_COUNT = getattr(_project, "ONTOGEN_CATEGORY_CURATION_TARGET_COUNT", None)
CATEGORY_CURATION_MIN_TARGET_COUNT = getattr(_project, "ONTOGEN_CATEGORY_CURATION_MIN_TARGET_COUNT", 1)
CATEGORY_CURATION_PROTECTED_CATEGORIES = getattr(
    _project,
    "ONTOGEN_CATEGORY_CURATION_PROTECTED_CATEGORIES",
    [],
)
CATEGORY_CURATION_MODEL = getattr(_project, "ONTOGEN_CATEGORY_CURATION_MODEL", CATEGORY_SYNTHESIS_MODEL)
CATEGORY_CURATION_BACKEND = getattr(_project, "ONTOGEN_CATEGORY_CURATION_BACKEND", CATEGORY_SYNTHESIS_BACKEND)
CATEGORY_CURATION_BASE_URL = getattr(_project, "ONTOGEN_CATEGORY_CURATION_BASE_URL", CATEGORY_SYNTHESIS_BASE_URL)
CATEGORY_CURATION_TEMPERATURE = getattr(_project, "ONTOGEN_CATEGORY_CURATION_TEMPERATURE", None)
CATEGORY_CURATION_NUM_CTX = getattr(_project, "ONTOGEN_CATEGORY_CURATION_NUM_CTX", CATEGORY_SYNTHESIS_NUM_CTX)
CATEGORY_CURATION_MAX_COMPLETION_TOKENS = getattr(
    _project,
    "ONTOGEN_CATEGORY_CURATION_MAX_COMPLETION_TOKENS",
    CATEGORY_SYNTHESIS_MAX_COMPLETION_TOKENS,
)
CATEGORY_CURATION_REASONING_EFFORT = getattr(_project, "ONTOGEN_CATEGORY_CURATION_REASONING_EFFORT", None)

# Taxonomy settings. CATEGORY_SEED_FILE can be None to use the first generated
# seed in CATEGORY_DIR for DOMAIN_NAME.
CATEGORY_SEED_FILE = getattr(_project, "ONTOGEN_CATEGORY_SEED_FILE", None)
TAXONOMY_MODEL = getattr(_project, "ONTOGEN_TAXONOMY_MODEL", "llama3.1:70b")
TAXONOMY_BACKEND = getattr(_project, "ONTOGEN_TAXONOMY_BACKEND", "ollama")
TAXONOMY_BASE_URL = getattr(_project, "ONTOGEN_TAXONOMY_BASE_URL", None)
TAXONOMY_TEMPERATURE = getattr(_project, "ONTOGEN_TAXONOMY_TEMPERATURE", 0.1)
TAXONOMY_NUM_CTX = getattr(_project, "ONTOGEN_TAXONOMY_NUM_CTX", 32000)
TAXONOMY_MAX_COMPLETION_TOKENS = getattr(_project, "ONTOGEN_TAXONOMY_MAX_COMPLETION_TOKENS", None)
TAXONOMY_REASONING_EFFORT = getattr(_project, "ONTOGEN_TAXONOMY_REASONING_EFFORT", None)
TAXONOMY_NUM_ITERATIONS = getattr(_project, "ONTOGEN_TAXONOMY_NUM_ITERATIONS", 5)
TAXONOMY_PROMPT_INCLUDE_PATH = False
TAXONOMY_SEED = getattr(_project, "ONTOGEN_TAXONOMY_SEED", 42)
TAXONOMY_SC_RETRY = getattr(_project, "ONTOGEN_TAXONOMY_SC_RETRY", 3)
TAXONOMY_MAJORITY = getattr(_project, "ONTOGEN_TAXONOMY_MAJORITY", None)
TAXONOMY_MAX_TERMS_PER_PAPER = getattr(_project, "ONTOGEN_TAXONOMY_MAX_TERMS_PER_PAPER", None)
TAXONOMY_MAX_TERM_CHARS = getattr(_project, "ONTOGEN_TAXONOMY_MAX_TERM_CHARS", None)

# Logging.
LOG_LEVEL = getattr(_project, "ONTOGEN_LOG_LEVEL", "INFO")


# =============================================================================
# Less frequently changed settings
# =============================================================================

NOUGAT_BATCHSIZE = None
NOUGAT_MODEL = None
NOUGAT_RECOMPUTE = False
NOUGAT_FULL_PRECISION = False
NOUGAT_MARKDOWN = True
NOUGAT_NO_SKIPPING = None
NOUGAT_PAGES = None
NOUGAT_THRESHOLD_NUM_REPETITIONS = 5

STRICT_SECTION_EXTRACTION = False
TABLE_OUTPUT_FORMAT = "both"
