from __future__ import annotations

"""
Heuristics to split scientific papers into named sections.

The original abstract/introduction helpers are kept for backward-compatible
CLI use. The newer extract_sections API writes section text plus JSONL
metadata with provenance for evidence-aware downstream processing.
"""

import argparse
import json
import logging
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

from utils import write_text

logger = logging.getLogger(__name__)


CANONICAL_SECTION_ORDER = [
    "abstract",
    "introduction",
    "methods",
    "experimental",
    "experiments",
    "evaluation",
    "results",
    "discussion",
    "ablation",
]

SECTION_ALIASES = {
    "abstract": [
        "abstract",
        "summary",
    ],
    "introduction": [
        "introduction",
        "background",
    ],
    "methods": [
        "method",
        "methods",
        "methodology",
        "materials and methods",
        "method and materials",
        "approach",
        "proposed method",
    ],
    "experimental": [
        "experimental",
        "experimental setup",
        "experiment setup",
        "experimental details",
        "implementation details",
    ],
    "experiments": [
        "experiment",
        "experiments",
        "experimental evaluation",
    ],
    "evaluation": [
        "evaluation",
        "evaluation setup",
        "benchmark evaluation",
    ],
    "results": [
        "results",
        "result",
        "results and discussion",
        "experimental results",
        "main results",
    ],
    "discussion": [
        "discussion",
        "discussion and conclusions",
    ],
    "ablation": [
        "ablation",
        "ablation study",
        "ablation studies",
        "ablations",
    ],
}

ALIAS_TO_SECTION = {
    alias: section
    for section, aliases in SECTION_ALIASES.items()
    for alias in aliases
}


@dataclass(frozen=True)
class SectionRecord:
    source_file: str
    paper_id: str
    section: str
    heading: str
    content: str
    start_line: int
    end_line: int


def postprocess_pymupdf_text(text):
    """
    Remove hyphens at the end of lines.
    Remove jump lines so as the resulting text is one line only.
    """
    lines = text.split("\n")
    processed_text = ""
    for line in lines:
        if line.endswith("-"):
            processed_text += line[:-1]
        else:
            processed_text += line + " "
    return processed_text


def extract_abstract_nougat(markdown_file):
    """
    Genrally speaking, nougat-generated markdown files have the abstract title marked with '#'.
    The content of the abstract, which is returned by this function is the second line after the abstract title.

    In some cases, the abstract is presented inline as follows:
       Abstract: lorem ipsum dolor sit amet, consectetur adipiscing elit....
    In such cases, if the word 'asbtract' is detected and the length of the line is over 100 characters
    (heuristic for abstract length, probably larger), then it is assumed that the abstract is in the same line.
    """
    ESTIMATED_MIN_LENGTH_ABSTRACT = 100
    ESTIMATED_MAX_LENGTH_ABSTRACT = 3000

    path = Path(markdown_file)
    text = path.read_text()
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if "abstract" in line.lower():
            # 1. Inline abstract case
            if (
                len(line) > ESTIMATED_MIN_LENGTH_ABSTRACT
                and len(line) < ESTIMATED_MAX_LENGTH_ABSTRACT
            ):
                return line
            # 2. Abstract title followed by content
            else:  # only the title is present
                # NOTE: In this case you can also check if line.startswith('#')
                probably_abstract = lines[i + 2]
                if (
                    len(probably_abstract) > ESTIMATED_MIN_LENGTH_ABSTRACT
                    and len(probably_abstract) < ESTIMATED_MAX_LENGTH_ABSTRACT
                ):
                    return probably_abstract

    # 'abstract' not found -> we fall to take the line previous to the 'introduction' section title
    for i, line in enumerate(lines):
        if "introduction" in line.lower():
            if (
                len(lines[i - 2]) > ESTIMATED_MIN_LENGTH_ABSTRACT
                and len(lines[i - 2]) < ESTIMATED_MAX_LENGTH_ABSTRACT
            ):
                return lines[i - 2]

    # 'abstract' and 'introduction' not found -> None
    return None


def extract_abstract_pymupdf(txt_file):
    """
    This function extracts the abstract from a text file generated by pyumpdf for Elsevier papers.
    In Elsevier papers parsed by pyumpdf, the abstract title is usually present in a single
    line in cumbersome ways such as 'A B S T R A C T'.
    An heuristic is used to determine the end of the abstract. The following checks are performed:
    - line contains 'introduction'
    - line contains 'keyword'
    - line contains '©'
    - line contains 'elsevier'
    """
    path = Path(txt_file)
    text = path.read_text()
    lines = text.split("\n")
    abstract = ""
    abstract_started = False
    for line in lines:
        if abstract_started:
            if heuristic_is_end_of_abstract(line):
                break
            abstract += line + "\n"
        # NOTE: we assume that the first line only containes the abstract title
        if "abstract" in line.lower().replace(" ", ""):
            abstract_started = True

    abstract = postprocess_pymupdf_text(abstract)
    return abstract


def heuristic_is_end_of_abstract(line):
    """
    Heuristic method to detect the end of the abstract section in a text file.
    The method is based entirely on exact string matching.
    """
    if "introduction" in line.lower():
        return True
    if "keyword" in line.lower():
        return True
    if "©" in line:
        return True
    if "elsevier" in line.lower():
        return True
    if "K E Y W O R D S" in line:
        return True
    if "I N T R O D U C T I O N" in line:
        return True
    if "doi" in line.lower():
        return True
    return False


def heuristic_is_start_of_introduction(line):
    """
    Heuristic method to detect the start of the introduction section in a text file.
    The method is based entirely on exact string matching.
    """
    if line.lower().startswith("introduction"):
        return True
    if line.lower().startswith("1."):
        return True
    return False


def heuristic_is_end_of_introduction(line):
    """
    Heuristic method to detect the end of the introduction section in a text file.
    The method is based entirely on exact string matching.
    """
    if line.lower().startswith("results"):
        return True
    if line.lower().startswith("method"):
        return True
    if line.lower().startswith("methodology"):
        return True
    if line.lower().startswith("experimental"):
        return True
    if line.lower().startswith("2."):
        return True
    return False


def extract_introduction_pymupdf(txt_file):
    """
    This function extracts the introduction from a text file generated by pyumpdf.

    Parameters:
    txt_file (str): Path to the text file.
    """
    path = Path(txt_file)
    text = path.read_text()
    lines = text.split("\n")
    introduction = ""
    introduction_started = False
    introduction_ended = False  # flag to determine wether the introduction was closed or end of file was reached
    for line in lines:
        if introduction_started:
            if heuristic_is_end_of_introduction(line):
                introduction_ended = True
                break
            introduction += line + "\n"
        else:
            if heuristic_is_start_of_introduction(line):
                introduction_started = True
    introduction = postprocess_pymupdf_text(introduction)
    if introduction_ended:
        return introduction
    else:
        return None


def extract_introduction_nougat(markdown_file):
    """
    Assumptions: Nougat processed papers start the introduction section with 'Introduction' or 'INTRODUCTION'.
                Line starts with '#'.
                Introduction section ends with a line starting with '#' appears.
                NOTE: the number of preceding '#' characters need to match the one of the introduction title.
                Otherwise, the function would skip possible subsections of the introduction.

    If no introduction is found, None is returned.
    """
    path = Path(markdown_file)
    text = path.read_text()
    lines = text.split("\n")
    introduction = ""
    hash_title = ""
    introduction_started = False
    introduction_ended = False  # flag to determine wether the introduction was closed or end of file was reached
    for line in lines:
        if introduction_started:
            if line.startswith(hash_title):
                introduction_ended = True
                break
            introduction += line + "\n"
        else:
            if "Introduction" in line or "INTRODUCTION" in line:
                hash_title = (
                    line.replace("Introduction", "")
                    .replace("INTRODUCTION", "")
                    .strip()
                )
                # find first space character
                pos_space = hash_title.find(" ")
                if pos_space != -1:
                    hash_title = hash_title[:pos_space]
                introduction_started = True

    if introduction_ended:
        return introduction
    else:
        return None


def normalize_heading(heading: str) -> str:
    normalized = heading.strip()
    normalized = re.sub(r"^#+\s*", "", normalized)
    normalized = re.sub(r"\\(?:sub)*section\*?\{(.+?)\}", r"\1", normalized)
    normalized = re.sub(r"^\d+(?:\.\d+)*\.?\s+", "", normalized)
    normalized = re.sub(r"^[IVXLC]+\.\s+", "", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"[:.\-–—]+$", "", normalized)
    normalized = re.sub(r"\s+", " ", normalized)
    compact = normalized.replace(" ", "")
    if compact.isalpha() and normalized.count(" ") >= max(len(compact) - 1, 1):
        normalized = compact
    return normalized.lower()


def canonical_section_for_heading(heading: str) -> str | None:
    normalized = normalize_heading(heading)
    if normalized in ALIAS_TO_SECTION:
        return ALIAS_TO_SECTION[normalized]
    for alias, section in ALIAS_TO_SECTION.items():
        if normalized.startswith(alias + ":"):
            return section
        if normalized.startswith(alias + " "):
            return section
    return None


def _nougat_heading(line: str) -> str | None:
    stripped = line.strip()
    if re.match(r"^#{1,6}\s+\S", stripped):
        return stripped.lstrip("#").strip()
    latex_match = re.match(r"^\\(?:sub)*section\*?\{(.+?)\}\s*$", stripped)
    if latex_match:
        return latex_match.group(1).strip()
    return None


def _plain_text_heading(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or len(stripped) > 120:
        return None
    normalized = normalize_heading(stripped)
    if normalized in ALIAS_TO_SECTION:
        return stripped
    if re.match(r"^\d+(?:\.\d+)*\.?\s+[A-Z][A-Za-z /&-]{2,}$", stripped):
        return stripped
    if re.match(r"^[IVXLC]+\.\s+[A-Z][A-Za-z /&-]{2,}$", stripped):
        return stripped
    if stripped.isupper() and any(alias in normalized for alias in ALIAS_TO_SECTION):
        return stripped
    return None


def _detect_section_headings(lines: list[str], source_type: str) -> list[tuple[int, str, str]]:
    headings = []
    heading_fn = _nougat_heading if source_type == "nougat" else _plain_text_heading
    for index, line in enumerate(lines):
        heading = heading_fn(line)
        if heading is None:
            continue
        section = canonical_section_for_heading(heading)
        if section is None:
            continue
        headings.append((index, heading, section))
    return headings


def _unique_sections(sections: Iterable[str]) -> list[str]:
    normalized_sections = []
    seen = set()
    for section in sections:
        canonical = section.lower().strip()
        if canonical not in SECTION_ALIASES:
            mapped = canonical_section_for_heading(canonical)
            if mapped is None:
                raise ValueError(
                    f"Unknown section '{section}'. Supported sections: {CANONICAL_SECTION_ORDER}"
                )
            canonical = mapped
        if canonical not in seen:
            normalized_sections.append(canonical)
            seen.add(canonical)
    return normalized_sections


def _records_from_headings(
    input_path: Path,
    lines: list[str],
    headings: list[tuple[int, str, str]],
    requested_sections: list[str],
) -> list[SectionRecord]:
    records = []
    seen_sections = set()
    paper_id = input_path.stem
    heading_positions = [pos for pos, _, _ in headings]
    for heading_index, (line_index, heading, section) in enumerate(headings):
        if section not in requested_sections or section in seen_sections:
            continue
        next_line_index = len(lines)
        if heading_index + 1 < len(heading_positions):
            next_line_index = heading_positions[heading_index + 1]
        content_lines = lines[line_index + 1 : next_line_index]
        content = "\n".join(content_lines).strip()
        if not content:
            logger.warning("Section '%s' in %s is empty.", section, input_path)
            continue
        records.append(
            SectionRecord(
                source_file=str(input_path),
                paper_id=paper_id,
                section=section,
                heading=heading,
                content=content,
                start_line=line_index + 2,
                end_line=next_line_index,
            )
        )
        seen_sections.add(section)
    return records


def _legacy_fallback_record(
    input_path: Path,
    section: str,
    source_type: str,
) -> SectionRecord | None:
    if section == "abstract":
        content = (
            extract_abstract_nougat(input_path)
            if source_type == "nougat"
            else extract_abstract_pymupdf(input_path)
        )
    elif section == "introduction":
        content = (
            extract_introduction_nougat(input_path)
            if source_type == "nougat"
            else extract_introduction_pymupdf(input_path)
        )
    else:
        content = None
    if not content:
        return None
    return SectionRecord(
        source_file=str(input_path),
        paper_id=input_path.stem,
        section=section,
        heading=section.title(),
        content=content.strip(),
        start_line=-1,
        end_line=-1,
    )


def write_section_records(records: list[SectionRecord], output_dir: Path, input_stem: str) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    for record in records:
        write_text(output_dir / f"{input_stem}.{record.section}.txt", record.content)

    jsonl_path = output_dir / f"{input_stem}.sections.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(asdict(record), ensure_ascii=False) + "\n")
    return jsonl_path


def extract_sections(
    input_path: Path,
    sections: list[str],
    output_dir: Path,
    source_type: str = "nougat",
    strict: bool = False,
) -> list[SectionRecord]:
    """
    Extract selected sections from Nougat markdown or PyMuPDF plain text.

    Parameters:
    input_path: Path
        Processed text/markdown file.
    sections: list[str]
        Canonical section names or aliases.
    output_dir: Path
        Directory where section txt files and JSONL metadata are written.
    source_type: str
        Either "nougat" or "pymupdf".
    strict: bool
        If True, raise when requested sections are missing. Otherwise warn.
    """
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    source_type = source_type.lower().strip()
    if source_type not in {"nougat", "pymupdf"}:
        raise ValueError("source_type must be either 'nougat' or 'pymupdf'.")
    requested_sections = _unique_sections(sections)

    text = input_path.read_text(encoding="utf-8", errors="ignore")
    lines = text.splitlines()
    headings = _detect_section_headings(lines, source_type)
    records = _records_from_headings(input_path, lines, headings, requested_sections)

    found_sections = {record.section for record in records}
    for section in requested_sections:
        if section in found_sections:
            continue
        fallback_record = _legacy_fallback_record(input_path, section, source_type)
        if fallback_record is not None:
            records.append(fallback_record)
            found_sections.add(section)

    missing_sections = [section for section in requested_sections if section not in found_sections]
    for section in missing_sections:
        logger.warning("Requested section '%s' was not found in %s.", section, input_path)
    if strict and missing_sections:
        raise ValueError(f"Missing requested sections in {input_path}: {missing_sections}")

    records.sort(
        key=lambda record: (
            CANONICAL_SECTION_ORDER.index(record.section),
            record.start_line if record.start_line >= 0 else 10**9,
        )
    )
    write_section_records(records, output_dir, input_path.stem)
    return records


def _sections_from_cli(args: argparse.Namespace) -> list[str]:
    sections = []
    if args.abstract:
        sections.append("abstract")
    if args.introduction:
        sections.append("introduction")
    if args.sections:
        sections.extend(args.sections)
    return sections


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Extract scientific paper sections from a text or markdown file."
    )
    parser.add_argument("txt_file", type=str, help="Path to the text file to process.")
    parser.add_argument(
        "--nougat",
        action="store_true",
        help="Extract section from nougat-generated markdown file.",
    )
    parser.add_argument(
        "--pymupdf",
        action="store_true",
        help="Extract section from pymupdf-generated text file.",
    )
    parser.add_argument("--abstract", action="store_true", help="Extract abstract section.")
    parser.add_argument("--introduction", action="store_true", help="Extract introduction section.")
    parser.add_argument(
        "--sections",
        nargs="+",
        help="Additional section names to extract, e.g. methods results ablation.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        help="Directory where section text files and JSONL metadata are written.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any requested section is missing.",
    )
    return parser


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    parser = build_arg_parser()
    args = parser.parse_args()

    source_path = Path(args.txt_file)
    source_type = "nougat" if args.nougat else "pymupdf" if args.pymupdf else None
    if source_type is None:
        print("Please specify either --nougat or --pymupdf.")
        raise SystemExit(1)

    sections_to_extract = _sections_from_cli(args)
    if not sections_to_extract:
        print("Please specify either --abstract, --introduction, or --sections.")
        raise SystemExit(1)

    output_dir = Path(args.output_dir) if args.output_dir else source_path.parent
    extract_sections(
        source_path,
        sections_to_extract,
        output_dir,
        source_type=source_type,
        strict=args.strict,
    )
